name: flutter_login
description: A new Flutter project.

version: 1.0.0+1

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    uuid: ^2.0.0
    get_version: ^0.0.8+5

    shared_preferences: ^0.5.6+1
    local_auth: ^0.6.1
    cupertino_icons: ^0.1.2
    persist_theme: ^1.6.0
    http: ^0.12.0+1
    json_annotation: ^3.0.0
    provider: ^4.0.2

    #kakao
    kakao_flutter_sdk: ^0.4.2
    #Secure Storage
    flutter_secure_storage: ^4.1.0

    firebase_messaging: ^10.0.2
    #app bar slides
    transparent_image: ^1.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: ^1.0.0
    json_serializable: ^3.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/login/
        - assets/images/
        - CHANGELOG.md
