name: duckie_app
description: A new Flutter project.

version: 1.0.0+1

environment:
    sdk: '>=2.14.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    uuid: ^3.0.5
    get_version: ^0.2.2

    cupertino_icons: ^1.0.3
    # http: ^0.12.0+1
    http: ^0.13.4
    json_annotation: ^4.3.0
    provider: ^6.0.1
    #kakao
    kakao_flutter_sdk: ^0.8.2
    #Secure Storage
    flutter_secure_storage: ^4.2.1

    # firebase_messaging: ^10.0.9
    #app bar slides
    transparent_image: ^2.0.0
    #무한 스크래핑
    flutter_bloc: ^0.13.0
    image_picker: ^0.8.4+4
    #editor
    flutter_quill: ^2.5.1
    # multi image
    file_picker: ^3.0.3
    permission_handler: ^8.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: ^1.0.0
    json_serializable: ^6.0.1

flutter:
    uses-material-design: true

    assets:
        - assets/login/
        - assets/images/
        - CHANGELOG.md
